# Site settings
title: 杨二郎的个人博客
email: yangerlanginfo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  杨二郎的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yangerlang.info" # the base hostname & protocol for your site
rss_url: /pages/feed.xml

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
twitter: masonsuyan
# weibo:    ID
github: suyan
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: http://7xsfm0.com1.z0.glb.clouddn.com/yangerlangavatar.jpg
favicon: http://7xsfm0.com1.z0.glb.clouddn.com/yangerlangavatar.jpg

# disqus 设置
disqus:
  shortname: yangerlang

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yangerlang.info

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
